"""init

Revision ID: ec24f6b48e0b
Revises: 
Create Date: 2026-05-15 10:55:51.588262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec24f6b48e0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencias',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('TiposIncidencias.ALUMBRADO', sa.Enum('BACHES', 'ALUMBRADO', 'BASURA', 'SEGURIDAD', 'EMERGENCIA', name='tiposincidencias'), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('id_ciudadano', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_ciudadano'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencias')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
